openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Emily
  license:
    name: The Apache License
servers:
  - url: http://emily.com
paths:
  /api/profiles:
    get:
      summary: List all profiles
      operationId: listProfiles
      tags:
        - profiles
      responses:
        '200':
          description: An array of profiles
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profiles"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new profile
      operationId: createProfile
      tags:
        - profiles
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/profiles/{profileId}:
    get:
      summary: Profile matching with Id
      operationId: showProfileById
      tags:
        - profiles
      parameters:
        - name: profileId
          in: path
          required: true
          description: The Id of the profile to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Detailed profile for profile Id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/schedules:
    get:
      summary: Retrieve all schedules for every profileId
      operationId: schedules
      tags:
        - schedules
      responses:
        '200':
          description: An array of schedules
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedules"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/activities/{activityId}:
    get:
      summary: Activity for matching activity Id
      operationId: activiity
      tags:
        - activities
      parameters:
        - name: activityId
          in: path
          required: true
          description: The Id of the activity to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Detailed activity for activity Id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedules"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Profile:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
          minimum: 1
          maximum: 6
        goals:
          type: array
          minItems: 4
          maxItems: 4
          items:
            type: string
            description: Order of goals for profile
            enum:
             - Didactic
             - Movement
             - Creativity
             - Relaxing
        profile_id:
          type: integer
          format: int32
    Profiles:
      type: array
      items:
        $ref: "#/components/schemas/Profile"
    Activity:
      type: object
      properties:
        title:
          type: string
        preparation:
          type: string
        description:
          type: string
        age_min:
          type: integer
          format: int32
          minimum: 1
          maximum: 6
        age_max:
          type: integer
          format: int32
          minimum: 1
          maximum: 6
        didactic:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        movement:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        creativity:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        relaxing:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        activity_id:
          type: integer
          format: int32
    ActivitiesSchedule:
      type: object
      properties:
        title:
          type: string
        duration:
          type: integer
          format: int32
        start_time:
          type: integer
          format: int32
        end_time:
          type: integer
          format: int32
        activity_id:
          type: integer
          format: int32
    Schedules:
      type: object
      properties:
        profile_id:
          type: array
          items:
            $ref: "#/components/schemas/ActivitiesSchedule"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string